# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quickstudy.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuickStudy(object):
    def setupUi(self, QuickStudy):
        QuickStudy.setObjectName("QuickStudy")
        QuickStudy.resize(971, 648)
        self.centralwidget = QtWidgets.QWidget(QuickStudy)
        self.centralwidget.setObjectName("centralwidget")
        self.topbar = QtWidgets.QFrame(self.centralwidget)
        self.topbar.setGeometry(QtCore.QRect(0, 0, 971, 41))
        self.topbar.setStyleSheet("background-color: black;\n"
"color: white;")
        self.topbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topbar.setObjectName("topbar")
        self.openmenu = QtWidgets.QPushButton(self.topbar)
        self.openmenu.setGeometry(QtCore.QRect(10, 10, 31, 23))
        self.openmenu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Downloads/download (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openmenu.setIcon(icon)
        self.openmenu.setObjectName("openmenu")
        self.label = QtWidgets.QLabel(self.topbar)
        self.label.setGeometry(QtCore.QRect(56, 10, 141, 20))
        font = QtGui.QFont()
        font.setFamily("FangSong")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(0, 40, 40, 611))
        self.sidebar.setStyleSheet("background-color: black;\n"
"color: white;")
        self.sidebar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebar.setObjectName("sidebar")
        self.createset = QtWidgets.QToolButton(self.sidebar)
        self.createset.setGeometry(QtCore.QRect(11, 21, 127, 25))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        self.createset.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../Downloads/download (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.createset.setIcon(icon1)
        self.createset.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.createset.setObjectName("createset")
        self.openset = QtWidgets.QToolButton(self.sidebar)
        self.openset.setGeometry(QtCore.QRect(11, 52, 93, 25))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        self.openset.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../Downloads/download (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openset.setIcon(icon2)
        self.openset.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.openset.setObjectName("openset")
       
        self.Header = QtWidgets.QWidget(self.centralwidget)
        self.Header.setGeometry(QtCore.QRect(40, 40, 931, 91))
        self.Header.setObjectName("Header")
    
        self.Body = QtWidgets.QWidget(self.centralwidget)
        self.Body.setGeometry(QtCore.QRect(40, 130, 931, 421))
        self.Body.setObjectName("Body")
        self.Footer = QtWidgets.QWidget(self.centralwidget)
        self.Footer.setGeometry(QtCore.QRect(40, 550, 931, 91))
        self.Footer.setObjectName("Footer")
        QuickStudy.setCentralWidget(self.centralwidget)

        self.retranslateUi(QuickStudy)
        QtCore.QMetaObject.connectSlotsByName(QuickStudy)

    def retranslateUi(self, QuickStudy):
        _translate = QtCore.QCoreApplication.translate
        QuickStudy.setWindowTitle(_translate("QuickStudy", "MainWindow"))
        self.label.setText(_translate("QuickStudy", "Monci QuickStudy"))
        self.createset.setText(_translate("QuickStudy", "     Create New Set"))
        self.openset.setText(_translate("QuickStudy", "    Open Set"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QuickStudy = QtWidgets.QMainWindow()
    ui = Ui_QuickStudy()
    ui.setupUi(QuickStudy)
    QuickStudy.show()
    sys.exit(app.exec_())
